from __future__ import annotations

from typing import List

from env.models import RequestExample


def load_examples() -> List[RequestExample]:
    return [
        RequestExample(
            request_id="REQ-001",
            method="GET",
            path="/search",
            headers={"Host": "shop.example.com", "Accept": "text/html"},
            query_params={"q": "<script>alert(1)</script>"},
            body="",
            source_ip="198.51.100.10",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["script", "xss", "block", "sanitize"],
            analyst_notes="Raw reflected script execution should be blocked at the edge, not only sanitized downstream.",
        ),
        RequestExample(
            request_id="REQ-002",
            method="GET",
            path="/search",
            headers={"Host": "shop.example.com", "Accept": "text/html"},
            query_params={"q": "%3Cscript%3Ealert(1)%3C/script%3E"},
            body="",
            source_ip="203.0.113.14",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="high",
            recommended_action="sanitize",
            explanation_keywords=["encoded", "script", "xss", "sanitize"],
            analyst_notes="URL-encoded reflected XSS payload should be detected after decoding and sanitized.",
        ),
        RequestExample(
            request_id="REQ-003",
            method="POST",
            path="/login",
            headers={"Host": "app.example.com", "Content-Type": "application/x-www-form-urlencoded"},
            query_params={},
            body="username=admin' OR '1'='1&password=test",
            source_ip="203.0.113.21",
            user_agent="curl/8.5.0",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["sql", "bypass", "authentication", "block"],
            analyst_notes="Classic authentication bypass attempt using SQL injection.",
        ),
        RequestExample(
            request_id="REQ-004",
            method="GET",
            path="/orders",
            headers={"Host": "api.example.com", "Accept": "application/json"},
            query_params={"id": "105 UNION SELECT credit_card FROM customers"},
            body="",
            source_ip="203.0.113.88",
            user_agent="sqlmap/1.8",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["union", "select", "sql", "block"],
            analyst_notes="UNION-based SQL injection attempts direct data extraction from the customer table.",
        ),
        RequestExample(
            request_id="REQ-005",
            method="POST",
            path="/api/archive",
            headers={"Host": "ops.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"target":"daily-reports; ls -la"}',
            source_ip="203.0.113.52",
            user_agent="python-requests/2.32.0",
            vulnerability_type="command_injection",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["command", "injection", "shell", "block"],
            analyst_notes="Command separator injection is present, but the endpoint is limited to an internal archival worker.",
        ),
        RequestExample(
            request_id="REQ-006",
            method="POST",
            path="/api/ping",
            headers={"Host": "infra.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"host":"127.0.0.1 && whoami"}',
            source_ip="192.0.2.15",
            user_agent="Go-http-client/1.1",
            vulnerability_type="command_injection",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["command", "injection", "whoami", "block"],
            analyst_notes="Shell chaining is present, but the payload is lower impact than direct file exfiltration.",
        ),
        RequestExample(
            request_id="REQ-007",
            method="GET",
            path="/images",
            headers={"Host": "cdn.example.com", "Accept": "image/webp,*/*"},
            query_params={"file": "../../etc/passwd"},
            body="",
            source_ip="192.0.2.77",
            user_agent="Mozilla/5.0",
            vulnerability_type="path_traversal",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["traversal", "path", "file", "block"],
            analyst_notes="Directory traversal is present, but the endpoint is sandboxed to a non-privileged file cache.",
        ),
        RequestExample(
            request_id="REQ-008",
            method="GET",
            path="/download",
            headers={"Host": "files.example.com", "Accept": "*/*"},
            query_params={"name": "..%2f..%2f..%2fvar%2flog%2fauth.log"},
            body="",
            source_ip="203.0.113.120",
            user_agent="Wget/1.21.4",
            vulnerability_type="path_traversal",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["encoded", "traversal", "file", "block"],
            analyst_notes="Encoded traversal payload targets authentication logs and should be blocked after URL decoding.",
        ),
        RequestExample(
            request_id="REQ-009",
            method="GET",
            path="/products",
            headers={"Host": "shop.example.com", "Accept": "application/json"},
            query_params={"category": "laptops", "sort": "price_asc"},
            body="",
            source_ip="198.51.100.33",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "normal", "allow", "benign"],
            analyst_notes="Benign catalog browsing request with expected parameters.",
        ),
        RequestExample(
            request_id="REQ-010",
            method="POST",
            path="/comments",
            headers={"Host": "community.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"post_id":42,"comment":"Nice post <img src=x onerror=alert(1)>"}',
            source_ip="198.51.100.81",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["xss", "script", "sanitize", "block"],
            analyst_notes="Stored event-handler XSS in a user comment should be rejected, not merely cleaned.",
        ),
        RequestExample(
            request_id="REQ-011",
            method="GET",
            path="/docs",
            headers={"Host": "help.example.com", "Accept": "text/html"},
            query_params={"topic": "how to use ls -la on linux"},
            body="",
            source_ip="198.51.100.150",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "documentation", "allow", "benign"],
            analyst_notes="Benign documentation search includes shell terms but does not attempt command execution.",
        ),
        RequestExample(
            request_id="REQ-012",
            method="POST",
            path="/account/email",
            headers={"Host": "app.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"email":"alice@example.com","display_name":"Alice&#x3c;script&#x3e;"}',
            source_ip="198.51.100.160",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="medium",
            recommended_action="sanitize",
            explanation_keywords=["encoded", "script", "xss", "sanitize"],
            analyst_notes="HTML entity encoded script markers should be sanitized before storage.",
        ),
        RequestExample(
            request_id="REQ-013",
            method="GET",
            path="/report",
            headers={"Host": "analytics.example.com", "Accept": "application/json"},
            query_params={"range": "7days", "sort": "name desc"},
            body="",
            source_ip="198.51.100.170",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "analytics", "allow", "benign"],
            analyst_notes="Sorting and date range parameters are normal analytics usage and should not be flagged as SQLi.",
        ),
        RequestExample(
            request_id="REQ-014",
            method="GET",
            path="/learn/sql",
            headers={"Host": "academy.example.com", "Accept": "text/html"},
            query_params={"q": "how to use union select in sql tutorial"},
            body="",
            source_ip="198.51.100.180",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "tutorial", "allow", "benign"],
            analyst_notes="This is an informational tutorial search containing SQL terms but no exploit attempt.",
        ),
        RequestExample(
            request_id="REQ-015",
            method="GET",
            path="/docs/cli",
            headers={"Host": "help.example.com", "Accept": "text/html"},
            query_params={"topic": "shell command ls -la reference"},
            body="",
            source_ip="198.51.100.181",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "reference", "allow", "benign"],
            analyst_notes="This is a documentation lookup for shell syntax, not a command injection payload.",
        ),
        RequestExample(
            request_id="REQ-016",
            method="POST",
            path="/admin/query",
            headers={"Host": "admin.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"name":"admin\'/**/OR/**/\'1\'=\'1","tenant":"blue"}',
            source_ip="203.0.113.220",
            user_agent="sqlmap/1.8",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["sql", "injection", "comment", "block"],
            analyst_notes="Comment-obfuscated SQL injection bypass should still be recognized as a critical attack.",
        ),
    ]
