from __future__ import annotations

from typing import Dict, List

from env.models import ActionType, ArtifactName, RequestExample


def _artifacts(
    payload_analysis: str,
    decoded_input: str,
    traffic_history: str,
    source_reputation: str,
    asset_context: str,
    playbook_guidance: str,
) -> Dict[ArtifactName, str]:
    return {
        "payload_analysis": payload_analysis,
        "decoded_input": decoded_input,
        "traffic_history": traffic_history,
        "source_reputation": source_reputation,
        "asset_context": asset_context,
        "playbook_guidance": playbook_guidance,
    }


def _useful(*actions: ActionType) -> List[ActionType]:
    return list(actions)


def load_examples() -> List[RequestExample]:
    return [
        RequestExample(
            request_id="REQ-001",
            queue="edge-waf",
            title="Search query contains reflected script tag",
            method="GET",
            path="/search",
            headers={"Host": "shop.example.com", "Accept": "text/html"},
            query_params={"q": "<script>alert(1)</script>"},
            body="",
            source_ip="198.51.100.10",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["xss", "script", "reflected", "block"],
            analyst_notes="Reflected script payload in a public search endpoint should be blocked.",
            artifacts=_artifacts(
                payload_analysis="Payload contains a raw <script>alert(1)</script> sequence in a reflected parameter.",
                decoded_input="No additional decoding required. The malicious script is visible in plaintext.",
                traffic_history="This IP generated three similar search probes in the last five minutes against other storefront paths.",
                source_reputation="IP has medium-risk reputation due to recent scanner-like bursts against web forms.",
                asset_context="The /search endpoint renders user input into HTML snippets for autocomplete previews.",
                playbook_guidance="Reflected script execution on public HTML endpoints is treated as XSS. Block when active exploit strings are present.",
            ),
            useful_actions=_useful("inspect_payload", "inspect_asset_context", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-002",
            queue="app-sensor",
            title="Encoded script markers in profile update",
            method="POST",
            path="/account/email",
            headers={"Host": "app.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"email":"alice@example.com","display_name":"Alice&#x3c;script&#x3e;"}',
            source_ip="198.51.100.160",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="medium",
            recommended_action="sanitize",
            explanation_keywords=["xss", "encoded", "script", "sanitize"],
            analyst_notes="Entity-encoded script markers should be sanitized before storage.",
            artifacts=_artifacts(
                payload_analysis="The display_name field contains HTML entity markers consistent with script-tag obfuscation.",
                decoded_input="Decoded display_name becomes: Alice<script>.",
                traffic_history="The account changed its profile fields twice today with no prior malicious activity.",
                source_reputation="Source IP belongs to a residential ISP with no meaningful abuse history.",
                asset_context="Display names are stored and later rendered in account settings and support dashboards.",
                playbook_guidance="Stored or reflected XSS markers that are obfuscated but user-controlled should be sanitized if business flow can continue safely.",
            ),
            useful_actions=_useful("inspect_payload", "decode_obfuscation", "inspect_asset_context", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-003",
            queue="auth-gateway",
            title="Authentication bypass syntax in login request",
            method="POST",
            path="/login",
            headers={"Host": "app.example.com", "Content-Type": "application/x-www-form-urlencoded"},
            query_params={},
            body="username=admin' OR '1'='1&password=test",
            source_ip="203.0.113.21",
            user_agent="curl/8.5.0",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["sql", "authentication", "bypass", "block"],
            analyst_notes="Classic auth-bypass SQL injection should be blocked immediately.",
            artifacts=_artifacts(
                payload_analysis="The username field contains quote termination followed by OR '1'='1, a classic boolean SQL injection pattern.",
                decoded_input="No decoding required. The payload is already in executable SQL-like form.",
                traffic_history="Same IP attempted twelve failed logins against admin and finance usernames during the last ten minutes.",
                source_reputation="IP is tagged high-risk by internal telemetry and previously associated with credential attacks.",
                asset_context="The /login endpoint fronts a production account system with privileged administrator access.",
                playbook_guidance="Authentication bypass or direct data access SQL injection is critical severity and should be blocked.",
            ),
            useful_actions=_useful("inspect_payload", "review_history", "inspect_asset_context", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-004",
            queue="db-monitor",
            title="UNION SELECT against order lookup",
            method="GET",
            path="/orders",
            headers={"Host": "api.example.com", "Accept": "application/json"},
            query_params={"id": "105 UNION SELECT credit_card FROM customers"},
            body="",
            source_ip="203.0.113.88",
            user_agent="sqlmap/1.8",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["sql", "union", "exfiltration", "block"],
            analyst_notes="UNION-based data extraction should be blocked as critical SQL injection.",
            artifacts=_artifacts(
                payload_analysis="Query parameter contains UNION SELECT credit_card FROM customers, indicating direct data extraction intent.",
                decoded_input="No hidden encoding found. Payload is immediately actionable as SQL injection syntax.",
                traffic_history="Previous requests from this IP enumerated numeric order IDs before switching to UNION probes.",
                source_reputation="User agent identifies as sqlmap and the source reputation score is severe.",
                asset_context="The /orders API is connected to production customer and payment metadata.",
                playbook_guidance="UNION-based extraction attempts against production APIs are critical and require a block action.",
            ),
            useful_actions=_useful("inspect_payload", "review_history", "check_source_reputation", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-005",
            queue="internal-api",
            title="Shell separator in archive target",
            method="POST",
            path="/api/archive",
            headers={"Host": "ops.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"target":"daily-reports; ls -la"}',
            source_ip="203.0.113.52",
            user_agent="python-requests/2.32.0",
            vulnerability_type="command_injection",
            severity="high",
            recommended_action="block",
            explanation_keywords=["command", "shell", "separator", "block"],
            analyst_notes="Command separator injection on an internal operations endpoint is high severity.",
            artifacts=_artifacts(
                payload_analysis="The target value appends '; ls -la', indicating shell command chaining after the expected argument.",
                decoded_input="No additional decoding needed. The shell separator is explicit.",
                traffic_history="This source tried similar archive requests against backup and restore endpoints earlier in the hour.",
                source_reputation="IP reputation is medium risk but linked to automation infrastructure rather than a normal employee workstation.",
                asset_context="The archive worker executes shell commands on a privileged internal batch host.",
                playbook_guidance="Shell separators or command chaining on execution-capable services should be blocked. Severity increases with privileged backend context.",
            ),
            useful_actions=_useful("inspect_payload", "inspect_asset_context", "review_history", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-006",
            queue="infra-api",
            title="Encoded shell chaining in ping utility",
            method="POST",
            path="/api/ping",
            headers={"Host": "infra.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"host":"127.0.0.1%20%26%26%20whoami"}',
            source_ip="192.0.2.15",
            user_agent="Go-http-client/1.1",
            vulnerability_type="command_injection",
            severity="high",
            recommended_action="block",
            explanation_keywords=["command", "encoded", "whoami", "block"],
            analyst_notes="Encoded shell chaining on an infrastructure helper endpoint should be blocked.",
            artifacts=_artifacts(
                payload_analysis="The host field contains encoded metacharacters consistent with shell chaining rather than a hostname.",
                decoded_input="Decoded host becomes: 127.0.0.1 && whoami.",
                traffic_history="Earlier requests from this IP tested single-host inputs before escalating to metacharacter probes.",
                source_reputation="Source reputation is low confidence, but activity is anomalous for this internal helper service.",
                asset_context="The ping utility shells out to system commands on a bastion-adjacent service.",
                playbook_guidance="When encoded shell operators appear in an execution-capable endpoint, classify as command injection and block.",
            ),
            useful_actions=_useful("inspect_payload", "decode_obfuscation", "inspect_asset_context", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-007",
            queue="cdn-edge",
            title="Directory traversal against image file parameter",
            method="GET",
            path="/images",
            headers={"Host": "cdn.example.com", "Accept": "image/webp,*/*"},
            query_params={"file": "../../etc/passwd"},
            body="",
            source_ip="192.0.2.77",
            user_agent="Mozilla/5.0",
            vulnerability_type="path_traversal",
            severity="high",
            recommended_action="block",
            explanation_keywords=["traversal", "path", "passwd", "block"],
            analyst_notes="Direct traversal to passwd should be blocked.",
            artifacts=_artifacts(
                payload_analysis="File parameter contains ../../etc/passwd, an attempt to escape the intended file directory.",
                decoded_input="No hidden encoding found. Traversal markers are explicit.",
                traffic_history="Two prior requests from the same source targeted /download and /thumbnail with the same traversal pattern.",
                source_reputation="Source reputation is moderate due to repeated reconnaissance across static-asset routes.",
                asset_context="The image service reads from a shared file cache mounted on Linux hosts.",
                playbook_guidance="Traversal attempts reaching sensitive filesystem paths are high severity and should be blocked.",
            ),
            useful_actions=_useful("inspect_payload", "review_history", "inspect_asset_context", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-008",
            queue="download-proxy",
            title="URL-encoded traversal aimed at auth logs",
            method="GET",
            path="/download",
            headers={"Host": "files.example.com", "Accept": "*/*"},
            query_params={"name": "..%2f..%2f..%2fvar%2flog%2fauth.log"},
            body="",
            source_ip="203.0.113.120",
            user_agent="Wget/1.21.4",
            vulnerability_type="path_traversal",
            severity="high",
            recommended_action="block",
            explanation_keywords=["traversal", "encoded", "log", "block"],
            analyst_notes="Encoded traversal targeting auth logs is high severity and should be blocked.",
            artifacts=_artifacts(
                payload_analysis="Parameter contains repeated encoded path separators suggestive of traversal.",
                decoded_input="Decoded name becomes ../../../var/log/auth.log.",
                traffic_history="Source previously requested several normal downloads before pivoting to sensitive log paths.",
                source_reputation="Source has medium-risk download abuse signals and no authenticated user context.",
                asset_context="The download service has access to application logs for support export jobs.",
                playbook_guidance="If decoding reveals traversal to system or log files, classify as path traversal and block.",
            ),
            useful_actions=_useful("inspect_payload", "decode_obfuscation", "inspect_asset_context", "consult_playbook"),
        ),
        RequestExample(
            request_id="REQ-009",
            queue="catalog-api",
            title="Normal product browsing request",
            method="GET",
            path="/products",
            headers={"Host": "shop.example.com", "Accept": "application/json"},
            query_params={"category": "laptops", "sort": "price_asc"},
            body="",
            source_ip="198.51.100.33",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "normal", "catalog", "allow"],
            analyst_notes="Expected browsing traffic with ordinary parameters.",
            artifacts=_artifacts(
                payload_analysis="Parameters are ordinary catalog filters with no executable metacharacters or traversal markers.",
                decoded_input="No encoded attack content detected after normalization.",
                traffic_history="User has a normal session path through homepage, search, and product browsing.",
                source_reputation="Source reputation is clean and consistent with residential consumer traffic.",
                asset_context="The endpoint is a read-only catalog API returning public product data.",
                playbook_guidance="Benign browsing traffic with no exploit indicators should be allowed.",
            ),
            useful_actions=_useful("inspect_payload", "review_history"),
        ),
        RequestExample(
            request_id="REQ-010",
            queue="docs-search",
            title="Documentation query mentioning shell commands",
            method="GET",
            path="/docs",
            headers={"Host": "help.example.com", "Accept": "text/html"},
            query_params={"topic": "how to use ls -la on linux"},
            body="",
            source_ip="198.51.100.150",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "documentation", "allow", "benign"],
            analyst_notes="The request references shell syntax in a harmless documentation context.",
            artifacts=_artifacts(
                payload_analysis="The terms look like documentation keywords, not shell metacharacters being sent to an execution endpoint.",
                decoded_input="No obfuscation present. Query remains a plain-language documentation search.",
                traffic_history="Same browser session previously viewed CLI tutorial pages and FAQ content.",
                source_reputation="Source reputation is clean with normal browsing cadence.",
                asset_context="The /docs endpoint is a static knowledge-base search page and does not execute commands.",
                playbook_guidance="Instructional or tutorial searches containing exploit vocabulary are safe when no execution context exists.",
            ),
            useful_actions=_useful("inspect_payload", "inspect_asset_context"),
        ),
        RequestExample(
            request_id="REQ-011",
            queue="analytics-ui",
            title="Benign report sorting with SQL-like wording",
            method="GET",
            path="/report",
            headers={"Host": "analytics.example.com", "Accept": "application/json"},
            query_params={"range": "7days", "sort": "name desc"},
            body="",
            source_ip="198.51.100.170",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["safe", "analytics", "sorting", "allow"],
            analyst_notes="The SQL-adjacent word desc is normal sort syntax for the analytics UI.",
            artifacts=_artifacts(
                payload_analysis="The request uses expected sort and date range parameters rather than query-breaking syntax.",
                decoded_input="Normalization preserves ordinary sort syntax with no injection payload.",
                traffic_history="The session includes dashboard navigation, filter adjustments, and export previews.",
                source_reputation="Source belongs to a trusted corporate SSO range.",
                asset_context="The report endpoint maps sort values to a fixed allowlist in the backend.",
                playbook_guidance="Analytics requests using allowed sort tokens are benign unless paired with SQL operators or quote termination.",
            ),
            useful_actions=_useful("inspect_payload", "inspect_asset_context", "review_history"),
        ),
        RequestExample(
            request_id="REQ-012",
            queue="admin-api",
            title="Obfuscated SQL injection against admin query endpoint",
            method="POST",
            path="/admin/query",
            headers={"Host": "admin.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"name":"admin\'/**/OR/**/\'1\'=\'1","tenant":"blue"}',
            source_ip="203.0.113.220",
            user_agent="sqlmap/1.8",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["sql", "obfuscated", "admin", "block"],
            analyst_notes="Comment-obfuscated bypass on an admin endpoint remains critical SQL injection.",
            artifacts=_artifacts(
                payload_analysis="Input contains quote termination, boolean logic, and comment-style separators consistent with obfuscated SQL injection.",
                decoded_input="Whitespace-normalized value reads like: admin' OR '1'='1.",
                traffic_history="Same source previously enumerated tenant IDs and then switched to admin query experimentation.",
                source_reputation="Source is severe-risk and explicitly uses sqlmap as the user agent.",
                asset_context="The endpoint is internal admin functionality with access to cross-tenant records.",
                playbook_guidance="Obfuscated SQL injection on privileged administration paths is critical and should be blocked immediately.",
            ),
            useful_actions=_useful("inspect_payload", "decode_obfuscation", "inspect_asset_context", "check_source_reputation", "consult_playbook"),
        ),
    ]
