from __future__ import annotations

from typing import List

from env.models import RequestExample


def load_examples() -> List[RequestExample]:
    return [
        RequestExample(
            request_id="REQ-001",
            method="GET",
            path="/search",
            headers={"Host": "shop.example.com", "Accept": "text/html"},
            query_params={"q": "<script>alert(1)</script>"},
            body="",
            source_ip="198.51.100.10",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="high",
            recommended_action="sanitize",
            explanation_keywords=["script", "payload", "xss", "reflected"],
            analyst_notes="Reflected XSS payload in search parameter should be neutralized.",
        ),
        RequestExample(
            request_id="REQ-002",
            method="POST",
            path="/login",
            headers={"Host": "app.example.com", "Content-Type": "application/x-www-form-urlencoded"},
            query_params={},
            body="username=admin' OR '1'='1&password=test",
            source_ip="203.0.113.21",
            user_agent="curl/8.5.0",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["or", "sql", "bypass", "authentication"],
            analyst_notes="Classic authentication bypass attempt using SQL injection.",
        ),
        RequestExample(
            request_id="REQ-003",
            method="POST",
            path="/api/export",
            headers={"Host": "ops.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"format":"csv","target":"reports; cat /etc/passwd"}',
            source_ip="203.0.113.52",
            user_agent="python-requests/2.32.0",
            vulnerability_type="command_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["command", "shell", "separator", "passwd"],
            analyst_notes="Shell metacharacter injection attempts to execute a second command.",
        ),
        RequestExample(
            request_id="REQ-004",
            method="GET",
            path="/images",
            headers={"Host": "cdn.example.com", "Accept": "image/webp,*/*"},
            query_params={"file": "../../etc/shadow"},
            body="",
            source_ip="192.0.2.77",
            user_agent="Mozilla/5.0",
            vulnerability_type="path_traversal",
            severity="high",
            recommended_action="block",
            explanation_keywords=["..", "path", "traversal", "sensitive"],
            analyst_notes="Directory traversal seeks access to protected system files.",
        ),
        RequestExample(
            request_id="REQ-005",
            method="GET",
            path="/products",
            headers={"Host": "shop.example.com", "Accept": "application/json"},
            query_params={"category": "laptops", "sort": "price_asc"},
            body="",
            source_ip="198.51.100.33",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["normal", "browse", "benign", "safe"],
            analyst_notes="Benign catalog browsing request with expected parameters.",
        ),
        RequestExample(
            request_id="REQ-006",
            method="POST",
            path="/comments",
            headers={"Host": "community.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"post_id":42,"comment":"Nice post <img src=x onerror=alert(1)>"}',
            source_ip="198.51.100.81",
            user_agent="Mozilla/5.0",
            vulnerability_type="xss",
            severity="medium",
            recommended_action="sanitize",
            explanation_keywords=["onerror", "html", "stored", "xss"],
            analyst_notes="Stored XSS content should be sanitized before storage or rendering.",
        ),
        RequestExample(
            request_id="REQ-007",
            method="GET",
            path="/orders",
            headers={"Host": "api.example.com", "Accept": "application/json"},
            query_params={"id": "105 UNION SELECT credit_card FROM customers"},
            body="",
            source_ip="203.0.113.88",
            user_agent="sqlmap/1.8",
            vulnerability_type="sql_injection",
            severity="critical",
            recommended_action="block",
            explanation_keywords=["union", "select", "sql", "exfiltration"],
            analyst_notes="SQL UNION payload attempts direct data extraction.",
        ),
        RequestExample(
            request_id="REQ-008",
            method="POST",
            path="/api/ping",
            headers={"Host": "infra.example.com", "Content-Type": "application/json"},
            query_params={},
            body='{"host":"127.0.0.1 && whoami"}',
            source_ip="192.0.2.15",
            user_agent="Go-http-client/1.1",
            vulnerability_type="command_injection",
            severity="high",
            recommended_action="block",
            explanation_keywords=["&&", "command", "shell", "whoami"],
            analyst_notes="User-controlled host field contains shell chaining for command execution.",
        ),
        RequestExample(
            request_id="REQ-009",
            method="GET",
            path="/profile",
            headers={"Host": "app.example.com", "Accept": "text/html"},
            query_params={"tab": "settings"},
            body="",
            source_ip="198.51.100.104",
            user_agent="Mozilla/5.0",
            vulnerability_type="safe",
            severity="none",
            recommended_action="allow",
            explanation_keywords=["normal", "profile", "expected", "safe"],
            analyst_notes="Authenticated user accessing a standard profile page.",
        ),
        RequestExample(
            request_id="REQ-010",
            method="GET",
            path="/download",
            headers={"Host": "files.example.com", "Accept": "*/*"},
            query_params={"name": "..%2f..%2f..%2fvar%2flog%2fauth.log"},
            body="",
            source_ip="203.0.113.120",
            user_agent="Wget/1.21.4",
            vulnerability_type="path_traversal",
            severity="medium",
            recommended_action="block",
            explanation_keywords=["encoded", "traversal", "log", "file"],
            analyst_notes="Encoded traversal payload targets server log files.",
        ),
    ]

